.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. detkcoin_qt test_detkcoin_qt
clean: FORCE
	$(MAKE) -C .. detkcoin_qt_clean test_detkcoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_detkcoin_qt_check
detkcoin-qt detkcoin-qt.exe: FORCE
	 $(MAKE) -C .. detkcoin_qt
